### ISSUE TITLE
Checkpoints URL ERROR

### ISSUE THREAD

**Issue by Nothing1024** [kakaobrain/rq-vae-transformer#10]
Hello! I want to get the checkpoints for test. But I found that they are unavaliable.
I try to ping the "https://arena.kakaocdn.net" By [PingPE](https://ping.pe/) and get the error connection message.

**Comment by LeeDoYup** [comment]
Although the checkpoints are available, you cannot access the https://arena.kakaocdn.net , since it's the address of our internal storage.

**Comment by Nothing1024** [comment]
So do I still have a chance to download the checkpoints? I tried to download the weights in `Checkpoints Used in the Original Paper` with `curl` and `wget` both failed.

**Comment by LeeDoYup** [comment]
I checked the url and still could download the checkpoints.
Did you check your environment setting?
