### ISSUE TITLE
using MSE loss to update cookbook?

### ISSUE THREAD

**Issue by shoutOutYangJie** [kakaobrain/rq-vae-transformer#13]
In your paper, you said that use EMA to update cookbook, but in your code,  you use MES to update latent code.

> loss_total = loss_recon + self.latent_loss_weight * loss_latent

**Comment by LeeDoYup** [comment]
Hello @shoutOutYangJie !
As described in our paper, we use the reconstruction loss and the commitment loss to train Encoder and Decoder of our RQ-VAE, and the codebook of RQ-VAE is updated by EMA. The codes, what you have mentioned, are loss for training encoder and decoder, not codebook.
