### ISSUE TITLE
The usage of soft codes

### ISSUE THREAD

**Issue by edward3862** [kakaobrain/rq-vae-transformer#15]
Thanks for your work! 
Does this function only work during the training of the transformer at stage 2?
https://github.com/kakaobrain/rq-vae-transformer/blob/2bf6ece4b85608cfae4c0e2969b17f75495e1639/rqvae/models/rqvae/quantizations.py#L372

**Comment by LeeDoYup** [comment]
Yes, we developed the `get_soft_codes`  module for the training of stage 2.
We described the details about the usage of soft codes in our paper.
