### ISSUE TITLE
Could you release the code for your new paper? Hierarchical VQ-VAE

### ISSUE THREAD

**Issue by zhangyingbit** [kakaobrain/rq-vae-transformer#20]
Sorry for inpterrupting!
I'm very interested in your paper "Locally Hierarchical Auto-Regressive Modeling for Image Generation, NIPS2022", could you release the code of this paper? I will be appreciated for that and thank you for the works in this paper~

**Comment by chiheonk** [comment]
Hi @zhangyingbit,

We currently have no plan yet to release the code of the mentioned paper. 

Since this issue is unrelated to the repo, I'm closing this issue but please contact the authors including us for further questions related to the mentioned paper.

**Comment by zhangyingbit** [comment]
> Hi @zhangyingbit,
> 
> We have a plan to release the code of the mentioned paper soon, but the exact date is not yet determined. We'll let you know if there's any update regarding the code release.
> 
> Since this issue is unrelated to the repo, I'm closing this issue but please contact the authors including us for further questions related to the mentioned paper.

Thank you for the reply and sorry for pulling the unrelated issue, looking forward to the code~

**Comment by chiheonk** [comment]
Hi @zhangyingbit,

The code for HQ-VAE and HQ-Transformer is now released at https://github.com/kakaobrain/hqtransformer.

**Comment by zhangyingbit** [comment]
> Hi @zhangyingbit,
> 
> The code for HQ-VAE and HQ-Transformer is now released at https://github.com/kakaobrain/hqtransformer.


Thank you so much for your notification and your effort for the code~
