### ISSUE TITLE
train rvq-vae using ffhq dataset:checkpointing is not compatible with .grad() or when an inputs parameter is passed to .backward()

### ISSUE THREAD

**Issue by xiapengchng** [kakaobrain/rq-vae-transformer#22]
![image](https://user-images.githubusercontent.com/32598987/222134410-19711a93-da20-42d0-93d0-afdb136180be.png)
![微信图片_20230301200448](https://user-images.githubusercontent.com/32598987/222134607-47abb3af-5bcb-438c-b217-6cefc2ea9995.png)
 
How to solve this runtime error? Thanks a lot!

**Comment by gnosisyuw** [comment]
This bascially means you did not initialize distributed learning correctly.

**Comment by Susmit-A** [comment]
How can this be fixed? I ran stage 1 training on a single node with 2 GPUs with the command `python main_stage1.py -m configs/imagenet256/stage1/in256-rqvae-8x8x4.yaml` and encountered the same error.

It worked when I used just 1 GPU by setting CUDA_VISIBLE_DEVICES.
