### ISSUE TITLE
cc3m_cc12m_yfcc archive is damaged?

### ISSUE THREAD

**Issue by andorxornot** [kakaobrain/rq-vae-transformer#4]
Can you check the file `cc3m_cc12m_yfcc.tar.gz, I have downloaded it twice and it is damaged.

**Comment by LeeDoYup** [comment]
When I have re-download and unzip the file, I check that there is no problem.
I think the issue is not related with the checkpoint file, but other problem.

**Comment by andorxornot** [comment]
yeah, i think I found the problem, if i download in one thread, the file downloads without errors. if i use multiple threads, the file gets corrupted

**Comment by oatmeal3000** [comment]
use curl to download
