### ISSUE TITLE
About the feature statistics of datasets

### ISSUE THREAD

**Issue by zqp111** [kakaobrain/rq-vae-transformer#6]
Hi, the feature statistics of datasets you provided on the [readme](https://arena.kakaocdn.net/brainrepo/etc/RQVAE/85114e40c0b49622ed92b1ab925e9785/fid_stats.tar.gz) seems has some problem. I downloaded it and found it was a link not real data. Could you please check it？

**Comment by LeeDoYup** [comment]
First of all, I check the file has no problem to download and unzip.
The red boxes below are the command in `README.md`.
![image](https://user-images.githubusercontent.com/33016192/160972708-3cb178f7-b8b3-482e-9bb1-a774da734c5d.png)

However, I found that the readme is not kind to load the feature statistics.
Actually, each `npz` file includes the statistics using `mu` and `sigma` as the keys of the `npz` file.

So, after you load the npz file, you can refer to the example below for using each mu and sigma.
<img width="829" alt="image" src="https://user-images.githubusercontent.com/33016192/160972986-4d1fa2c8-c8f6-4a8b-be6d-e5654d7cfcf7.png">

It is related to this.
https://github.com/kakaobrain/rq-vae-transformer/blob/c3de514d7c832f63eff333833b456c53a342e8c0/rqvae/metrics/fid.py#L305

**Comment by zqp111** [comment]
I think it work on you PC because the data you upload is a link, this is the situation on my computer.
![image](https://user-images.githubusercontent.com/32261422/160974638-7c19bd19-6952-40c4-aa34-2677bd0d0fa8.png)
It seems to be a link.

**Comment by LeeDoYup** [comment]
Oh, we check that we cannot download the files. We will resolve this issue

**Comment by LeeDoYup** [comment]
@zqp111 We update the link and please check it.
After checking, please close this issue !!
