### ISSUE TITLE
Are there any plans to release pre-trained RQ-VAEs with different shapes?

### ISSUE THREAD

**Issue by qwopqwop200** [kakaobrain/rq-vae-transformer#7]
Are there any plans to release a pre-trained RQ-VAE with the shape of 8 x 8 x 2,8 x 8 x 8,8 x 8 x 16?

**Comment by LeeDoYup** [comment]
We are not considering it right now.
However, if we decide to upload the checkpoints, I will make a mention(@) in this thread.
