### ISSUE TITLE
gpu memory enough for inference

### ISSUE THREAD

**Issue by mkaskov** [kakaobrain/rq-vae-transformer#8]
if I don't have 32GB memory GPU
can I start for inference any model on 11GB gtx1080ti?

**Comment by LeeDoYup** [comment]
You cannot load the 3.9B parameters of model on 11GB GTB1080Ti, but you can try to load 650M T2I model (trained on CC3M). We are going to release 1.4B parameters of T2I model trained on 30M text-image pairs, thank you !
